Repository ubccr/xdmod-data, pull requests merged in 2025-01, with the labels that each got.

#44 Prepare for v1.1.0 development.
  .github/workflows/xdmod-data.yml
  CHANGELOG.md
  docs/developing.md
  xdmod_data/__version__.py
Labels: release prep

#45 Implement 100% test coverage.
  .github/PULL_REQUEST_TEMPLATE.md
  CHANGELOG.md
  docs/developing.md
  tests/integration/test_datawarehouse_integration.py
  tests/regression/data/jobs-2022-2023-years.csv
  tests/regression/data/jobs-2023-quarters.csv
  tests/regression/test_datawarehouse_regression.py
  tests/unit/test_datawarehouse_unit.py
  xdmod_data/__version__.py
  xdmod_data/_descriptors.py
  xdmod_data/_http_requester.py
  xdmod_data/_response_processor.py
  xdmod_data/_validator.py
Labels: documentation, qa/testing

#28 Update Flake8 rules
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/xdmod-data.yml
  CHANGELOG.md
  docs/developing.md
  tests/integration/test_datawarehouse_integration.py
  tests/regression/data/jobs-2023-months.csv
  tests/regression/test_datawarehouse_regression.py
  tests/unit/test_datawarehouse_unit.py
  xdmod_data/__version__.py
  xdmod_data/_descriptors.py
  xdmod_data/_http_requester.py
  xdmod_data/_response_processor.py
  xdmod_data/_validator.py
  xdmod_data/themes.py
Labels: qa/testing

#46 Update Flake8 rules
  .github/workflows/xdmod-data.yml
  CHANGELOG.md
  docs/developing.md
  tests/integration/test_datawarehouse_integration.py
  tests/regression/data/jobs-2023-months.csv
  tests/regression/test_datawarehouse_regression.py
  tests/unit/test_datawarehouse_unit.py
  xdmod_data/__version__.py
  xdmod_data/_descriptors.py
  xdmod_data/_http_requester.py
  xdmod_data/_response_processor.py
  xdmod_data/_validator.py
  xdmod_data/themes.py
Labels: qa/testing

#48 Add stub CircleCI config.
  .circleci/config.yml
  CHANGELOG.md
  xdmod_data/__version__.py
Labels: qa/testing

#49 Set up CircleCI.
  .circleci/config.yml
  .github/workflows/xdmod-data.yml
  CHANGELOG.md
  docs/developing.md
  xdmod_data/__version__.py
Labels: qa/testing

#50 Change to using CircleCI instead of GitHub Actions for continuous integration.
  .circleci/config.yml
  .github/workflows/xdmod-data.yml
  CHANGELOG.md
  docs/developing.md
  xdmod_data/__version__.py
Labels: qa/testing

#51 Set up Docker Compose for CI testing.
  .circleci/config.yml
  .circleci/docker-compose.yml
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  CHANGELOG.md
  docs/developing.md
  tests/ci/artifacts/10000users.log
  tests/integration/test_datawarehouse_integration.py
  tests/regression/data/default/jobs-2016-2017-month.csv
  tests/regression/data/default/jobs-2016-2017-quarters.csv
  tests/regression/data/default/jobs-2016-2017-years.csv
  tests/regression/data/default/jobs-dimensions.csv
  tests/regression/data/default/jobs-metrics.csv
  tests/regression/data/default/jobs-pi-group-filter-values.csv
  tests/regression/data/default/raw-data-every-1000-no-fields-no-filters.csv
  tests/regression/data/default/raw-data-every-1000-with-fields-and-filters.csv
  tests/regression/data/default/realms.csv
  tests/regression/data/jobs-2022-2023-years.csv
  tests/regression/data/jobs-2023-months.csv
  tests/regression/data/jobs-2023-quarters.csv
  tests/regression/data/jobs-dimensions.csv
  tests/regression/data/jobs-fieldofscience-filter-values.csv
  tests/regression/data/jobs-metrics.csv
  tests/regression/data/machine-learning-notebook-example-every-1000.csv
  tests/regression/data/realms.csv
  tests/regression/data/xdmod-10-5/jobs-dimensions.csv
  tests/regression/data/xdmod-10-5/jobs-metrics.csv
  tests/regression/data/xdmod-10-5/raw-data-every-1000-no-fields-no-filters.csv
  tests/regression/data/xdmod-10-5/raw-data-every-1000-with-fields-and-filters.csv
  tests/regression/data/xdmod-10-5/realms.csv
  tests/regression/test_datawarehouse_regression.py
  tests/unit/test_datawarehouse_unit.py
  xdmod_data/__version__.py
  xdmod_data/_http_requester.py
  xdmod_data/_response_processor.py
Labels: qa/testing

#52 Add XDMoD 11.0 development version to CI testing.
  .circleci/config.yml
  .circleci/docker-compose.yml
  CHANGELOG.md
  xdmod_data/__version__.py
Labels: qa/testing

#53 Docker compose 1.x.y
  .circleci/config.yml
  .circleci/docker-compose.yml
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  CHANGELOG.md
  docs/developing.md
  tests/ci/artifacts/10000users.log
  tests/integration/test_datawarehouse_integration.py
  tests/regression/data/default/jobs-2016-2017-month.csv
  tests/regression/data/default/jobs-2016-2017-quarters.csv
  tests/regression/data/default/jobs-2016-2017-years.csv
  tests/regression/data/default/jobs-dimensions.csv
  tests/regression/data/default/jobs-metrics.csv
  tests/regression/data/default/jobs-pi-group-filter-values.csv
  tests/regression/data/default/raw-data-every-1000-no-fields-no-filters.csv
  tests/regression/data/default/raw-data-every-1000-with-fields-and-filters.csv
  tests/regression/data/default/realms.csv
  tests/regression/data/jobs-2022-2023-years.csv
  tests/regression/data/jobs-2023-months.csv
  tests/regression/data/jobs-2023-quarters.csv
  tests/regression/data/jobs-dimensions.csv
  tests/regression/data/jobs-fieldofscience-filter-values.csv
  tests/regression/data/jobs-metrics.csv
  tests/regression/data/machine-learning-notebook-example-every-1000.csv
  tests/regression/data/realms.csv
  tests/regression/data/xdmod-10-5/jobs-dimensions.csv
  tests/regression/data/xdmod-10-5/jobs-metrics.csv
  tests/regression/data/xdmod-10-5/raw-data-every-1000-no-fields-no-filters.csv
  tests/regression/data/xdmod-10-5/raw-data-every-1000-with-fields-and-filters.csv
  tests/regression/data/xdmod-10-5/realms.csv
  tests/regression/test_datawarehouse_regression.py
  tests/unit/test_datawarehouse_unit.py
  xdmod_data/__version__.py
  xdmod_data/_http_requester.py
  xdmod_data/_response_processor.py
Labels: qa/testing

#56 Test minimum dependency versions in CircleCI.
  .circleci/config.yml
  CHANGELOG.md
  xdmod_data/__version__.py
Labels: qa/testing

#58 Move CI testing into a script file.
  .circleci/config.yml
  CHANGELOG.md
  docs/developing.md
  tests/ci/scripts/docker-compose.yml
  tests/ci/scripts/run-tests.sh
  xdmod_data/__version__.py
Labels: qa/testing

#57 Test minimum dependency versions in CircleCI.
  .circleci/config.yml
  CHANGELOG.md
  xdmod_data/__version__.py
Labels: qa/testing

#59 Move CI testing into a script file.
  .circleci/config.yml
  CHANGELOG.md
  docs/developing.md
  tests/ci/scripts/docker-compose.yml
  tests/ci/scripts/run-tests.sh
Labels: qa/testing

#60 Fix Plotly template ValueError.
  CHANGELOG.md
  xdmod_data/__version__.py
  xdmod_data/themes.py
Labels: bug

#61 Fix Plotly template ValueError.
  CHANGELOG.md
  xdmod_data/__version__.py
  xdmod_data/themes.py
Labels: bug

#63 Release version 1.0.3.
  CHANGELOG.md
  README.md
  docs/developing.md
  setup.cfg
  xdmod_data/__version__.py
Labels: release prep

#64 Release v1.0.3.
  CHANGELOG.md
  README.md
  docs/developing.md
  xdmod_data/__version__.py
Labels: release prep

#66 Update development instructions.
  CHANGELOG.md
  docs/developing.md
  xdmod_data/__version__.py
Labels: documentation
